config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :animals
  devise_for :users, controllers: {registrations: "users/registrations"}

  root to: "pages#index"

  get "/home", to: "pages#home", as: "user_home"
  get "/account", to: "pages#account", as: "user_account"
  get "/contact", to: "pages#contact", as: "contact"
  get "/admin-dashboard", to: "pages#admin", as: "admin"
  get "/admin-view/:id", to: "pages#admin_view_user", as: "admin_user"
  post "/admin-approve/:id", to: "pages#admin_approve_user", as: "admin_user_approve"
  post "/admin-deny/:id", to: "pages#admin_deny_user", as: "admin_user_deny"
  post "/animals/media/:id", to: "animals#media_add", as: "animals_media"
  delete "/animals/media/:id", to: "animals#media_delete"
  post "/animals/new_message/:id", to: "animals#new_message", as: "new_message"
  get "/payments/success", to: "payments#success", as: "payment_success"
  post "/payments/webhook", to: "payments#webhook", as: "webhook"
  post "/payments", to: "payments#create_payment_intent", as: "create_payment"
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light <%= !@landing.present? ? "bg-dark-body border-bottom" : "" %>">
  <%= link_to root_path, class: "navbar-brand", id: "brand" do %>
    <%= image_tag "logo.png", width: 40, height: 30, class: "d-inline-block align-top" %>
     StB
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarItems" aria-controls="navbarItems" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarItems">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item <%= "#{set_nav_item_active(root_path)} #{set_nav_item_active(user_home_path)}" %>">
        <%= link_to "Home", root_path, class: "nav-link", aria: {current: true} %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle <%= "#{set_nav_item_active(animals_path)} #{set_nav_item_active(new_animal_path)}" %>" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Animals</a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "All Animals", animals_path, class: "dropdown-item" %>
            <%= link_to "Post an Animal", new_animal_path, class: "dropdown-item #{display_post_animal}" %>
          </div>
      </li>
      <li class="nav-item <%= set_nav_item_active(contact_path) %>">
        <%= link_to "Contact", contact_path, class: "nav-link" %>
      </li>
      <% if current_user&.admin? %>
        <li class="nav-item <%= set_nav_item_active(admin_path) %>">
          <%= link_to "Admin", admin_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item <%= set_nav_item_active(user_account_path) %>">
          <%= link_to "Account", user_account_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item <%= set_nav_item_active(new_user_session_path) %>">
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>