config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :animals
  devise_for :users, controllers: {registrations: "users/registrations"}

  root to: "pages#index"

  get "/home", to: "pages#home", as: "user_home"
  get "/account", to: "pages#account", as: "user_account"
  get "/contact", to: "pages#contact", as: "contact"
  get "/admin-dashboard", to: "pages#admin", as: "admin"
  get "/admin-view/:id", to: "pages#admin_view_user", as: "admin_user"
  post "/admin-approve/:id", to: "pages#admin_approve_user", as: "admin_user_approve"
  post "/admin-deny/:id", to: "pages#admin_deny_user", as: "admin_user_deny"
  post "/animals/media/:id", to: "animals#media_add", as: "animals_media"
  delete "/animals/media/:id", to: "animals#media_delete"
  post "/animals/new_message/:id", to: "animals#new_message", as: "new_message"
  get "/payments/success", to: "payments#success", as: "payment_success"
  post "/payments/webhook", to: "payments#webhook", as: "webhook"
  post "/payments", to: "payments#create_payment_intent", as: "create_payment"
end

app/views/pages/account.html.erb
<% content_for(:html_title) { 'Account' } %>
<main class="container">
    <div class="row justify-content-center text-center">
        <h1>Account</h1>
    </div>
    <div class="row mt-5">
        <article class="col-4">
            <h3>Details:</h3>
            <ul class="list-group list-group-flush mb-3">
                <li class="list-group-item"><h6 class="d-inline">Name:</h6> <%= current_user&.full_name %></li>
                <li class="list-group-item"><h6 class="d-inline">Email:</h6> <address class="d-inline"><%= current_user&.email %></address></li>
                <li class="list-group-item"><h6 class="d-inline">Account Type:</h6> <%= current_user&.role %></li>
                <li class="list-group-item"><h6 class="d-inline">Location:</h6> <address class="d-inline"><%= current_user&.get_simple_location %></address></li>
            </ul>
            <%= link_to "Edit Account", edit_user_registration_path, class: "mr-3" %>
            <%= link_to "Delete Account", user_registration_path, method: :delete, data: {confirm: "Are you sure?"} %>
        </article>
        <article class="col-8 text-center">
            <h3 class="mb-3">Your <%= current_user&.sanctuary? ? "Sanctuaries" : "Sponsored" %> Animals:</h3>
            <section class="d-flex flex-wrap justify-content-end">
                <% @user_animals.each do |animal| %>
                    <div class="w-50 text-center" style="min-width: 150px;">
                        <%= link_to animal_path(animal), class: "text-primary" do %>
                            <%= render partial: "animals/card", locals: {animal: animal}%>
                        <% end %>
                    </div>
                <% end %>
            </section>
        </article>
    </div>
</main>

app/views/pages/admin.html.erb
<% content_for(:html_title) { 'Admin Dashboard' } %>
<main class="container">
    <div class="row text-center justify-content-center mb-5">
        <h1>Admin - Dashboard</h1>
    </div>
    <div class="row justify-content-center">
        <section class="col justify-content-center text-center">
            <h3>Sanctuaries Awaiting Approval:</h3>
            <% if @unapproved.length == 0 %>  
                <p>There's nothing to display here.</p>          
            <% end %>
            <% @unapproved.each do |user| %>
                <div class="mt-2 mb-3">
                    <p><%= user.full_name %></p>
                    <%= link_to "View User Info", admin_user_path(user.id) %>
                    <%= link_to "Approve", admin_user_approve_path(user.id), method: :post %>
                    <%= link_to "Deny", admin_user_deny_path(user.id), method: :post %>
                </div>
            <% end %>
        </section>
        <section class="col justify-content-center text-center">
            <h3>Approved Accounts:</h3>
            <% @users.each do |user| %>
                <div class="mt-2 mb-3">
                    <p><%= user.full_name %> - <%= user.role.capitalize %></p>
                    <%= link_to "View", admin_user_path(user.id), class: "mr-3"%>
                    <%= link_to "Delete", admin_user_deny_path(user.id), method: :post %>
                </div>
            <% end %>        
        </section>
    </div>
</main>

app/views/pages/admin_view_user.html.erb
<% content_for(:html_title) { 'View User' } %>
<main class="container text-center w-50">
    <h1>View User</h1>
    <ul class="list-group list-group-flush">
        <li class="list-group-item"><u><h6 class="d-inline">Name:</h6></u> <%= @user.full_name %></li>
        <li class="list-group-item"><u><h6 class="d-inline">E-mail:</h6></u> <address class="d-inline"><%= @user.email %></address></li>
        <li class="list-group-item"><u><h6 class="d-inline">DOB:</h6></u> <%= @user.date_of_birth %></li>
        <li class="list-group-item"><u><h6 class="d-inline">Role:</h6></u> <%= @user.role.capitalize %></li>
        <li class="list-group-item"><u><h6 class="d-inline">Address:</h6></u> <address class="d-inline"><%= @user.get_full_location %></address></li>
    </ul>
    <%= link_to "Back", admin_path, class: "btn btn-primary mb-5 mr-3"%>
    <%= link_to "Delete", admin_user_deny_path(@user.id), method: :post, class: "btn btn-primary mb-5" %>
</main>

app/views/pages/contact.html.erb
<% content_for(:html_title) { 'Contact' } %>
<main class="text-center">
<h1 class="mb-3">Contact</h1>
<p>Any questions, please contact us at <address>contact@savetheirbacon.com</address></p>
</main>

app/views/pages/home.html.erb
<% content_for(:html_title) { 'Home' } %>
<main class="container rounded">
   <div class="row text-center justify-content-center mb-2 mb-md-5">
      <h1>Welcome, <%= current_user.first_name %>!</h1>
   </div>
   <div class="row justify-content-center order-1">
      <div class="col d-flex flex-column">
         <h3>News and Updates</h3>
         <ul class="list-group list-group-flush">
            <% @articles.each_with_index do |article, i| %>
               <li class="list-group-item bg-new-bg">
                  <%= link_to article.title, article_path(article), class: "mt-2 mb-2 text-body"%>
                  <% if i == 0 %>
                     <span class="badge badge-primary badge-pill ml-2">New!</span>
                  <% end %>
               </li>
            <% end %>
         </ul>
         <% if current_user&.admin? %>
            <%= link_to "Create Article", new_article_path %>
         <% end %>
      </div>
      <div class="col justify-content-center text-center order-3">
         <h3>Todays Featured Animal:</h3>
         <div style="max-height: 200px;">
         <%= link_to animal_path(@featured_animal), class: "text-primary" do %>
            <%= render partial: "animals/card", locals: {animal: @featured_animal}%>
         <% end %>
         </div>
      </div>
      <div class="col-6 text-center d-flex flex-column justify-content-around mt-2 mt-md-5 order-4 order-md-2">
         <%= link_to "Check in on your animals", user_account_path, class: "btn btn-primary btn-lg" %>
         <%= link_to "View all the animals", animals_path, class: "btn btn-primary btn-lg mt-1" %>
      </div>
   </div>
</main>

   

app/views/pages/index.html.erb
<% content_for(:html_title) { 'SaveTheirBacon' } %>
<main>
    <div class="jumbotron text-center mx-auto" id="landing-jumbo">
        <h1 class="display-4 text-primary font-weight-bold">Save Their Bacon</h1>
        <p class="lead text-dark-body">Find a rescued animal to sponsor, or find sponsors for your sanctuaries animals</p>
        <hr class="bg-primary" />
        <p class="lead mt-3 text-dark-body">Get Started! Are you a: </p>
        <%= link_to "Sponsor", new_user_registration_path(role: :sponsor), class: "btn btn-secondary btn-lg mr-3 mt-4" %>            
        <%= link_to "Sanctuary", new_user_registration_path(role: :sanctuary), class: "btn btn-secondary btn-lg mt-4" %>
    </div>
</main>