config/routes.rb
Rails.application.routes.draw do
  resources :articles
  resources :animals
  devise_for :users, controllers: {registrations: "users/registrations"}

  root to: "pages#index"

  get "/home", to: "pages#home", as: "user_home"
  get "/account", to: "pages#account", as: "user_account"
  get "/contact", to: "pages#contact", as: "contact"
  get "/admin-dashboard", to: "pages#admin", as: "admin"
  get "/admin-view/:id", to: "pages#admin_view_user", as: "admin_user"
  post "/admin-approve/:id", to: "pages#admin_approve_user", as: "admin_user_approve"
  post "/admin-deny/:id", to: "pages#admin_deny_user", as: "admin_user_deny"
  post "/animals/media/:id", to: "animals#media_add", as: "animals_media"
  delete "/animals/media/:id", to: "animals#media_delete"
  post "/animals/new_message/:id", to: "animals#new_message", as: "new_message"
  get "/payments/success", to: "payments#success", as: "payment_success"
  post "/payments/webhook", to: "payments#webhook", as: "webhook"
  post "/payments", to: "payments#create_payment_intent", as: "create_payment"
end

app/models/animal.rb
class Animal < ApplicationRecord
  before_create :capitalize_name
  belongs_to :category
  belongs_to :owner, foreign_key: "owner_id", class_name: "User"
  has_one :sponsorship
  has_one_attached :profile_picture
  has_many_attached :media

  validates :name, presence: true
  validates :year_born, numericality: {only_integer: true}, presence: true
  validates :weight, numericality: true, presence: true
  validates :bio, presence: true
  validates :species, presence: true
  validates :sponsor_price, presence: true, numericality: true

  def get_age
    Time.now.year - self.year_born
  end 

  private

  def capitalize_name
    self.name = self.name.capitalize
  end
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: %i[ show edit update destroy media_add media_delete new_message]
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :check_approved, only: [:new, :edit, :destroy]
  before_action :redirect_sponsor, only: [:new, :edit, :destroy]
  before_action :get_categories, only: [:index, :new, :edit]
  before_action :check_ownership, only: [:edit, :delete]

  # GET /animals or /animals.json
  def index
    #set @animals to all and keep updating based on search queries
    #rails combines all the where queries into 1.
    @animals = Animal.all
    if params[:category]
      if @categories.all.map {|c| c.id}.include? params[:category].to_i
        @animals = @animals.where(category_id: params[:category])
      end
    end
    if params[:sponsored]
      case params[:sponsored]
      when "0"
        @animals = @animals.where(sponsored: false)
      when "1"
        @animals = @animals.where(sponsored: true)
      end
    end
    if params[:name]
      if !params[:name].empty?
        @animals = @animals.where("name like ?", "%#{params[:name].downcase}%")
      end
    end
  end

  # GET /animals/1 or /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals or /animals.json
  def create
    price_dollars = params[:animal][:sponsor_price].to_f
    price_cents = (price_dollars * 100.0).to_i
    @animal = Animal.new(animal_params)
    @animal.sponsor_price = price_cents
    @animal.owner = current_user

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: "Animal was successfully created." }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1 or /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: "Animal was successfully updated." }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1 or /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: "Animal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # update @animal to attach pictures
  def media_add
    params[:media]&.each do |img|
      @animal.media.attach img
    end
    redirect_back(fallback_location: animal_path(@animal))
  end

  # delete specific attachment from @animal
  def media_delete
    @animal.media.find(params[:media_id]).purge
    redirect_back(fallback_location: animal_path(@animal))
  end

  def new_message
    Message.create(body: params[:message], sender_id: current_user.id, chat_id: @animal.sponsorship.chat.id)
    redirect_back(fallback_location: animal_path(@animal))
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.includes(:owner, :category).find(params[:id])
    end

    def get_categories
      @categories = Category.all
    end

    # redirect a user if they are a sponsor
    def redirect_sponsor
      redirect_to animals_path, notice: "sponsors do not have access to this" if current_user&.sponsor?
    end

    # Only allow a list of trusted parameters through.
    def animal_params
      params.require(:animal).permit(:name, :year_born, :weight, :bio, :species, :sponsored, :sponsor_price, :category_id, :owner_id, :profile_picture, media: [])
    end

    # redirect a user if they are not approved
    def check_approved
      redirect_to animals_path, notice: "Your account is not yet approved, you can't list an animal." if !current_user&.approved?
    end

    # redirect a user if they are not the animals owner
    def check_ownership
      redirect_to animals_path, notice: "You are not authorized for that action." if !current_user&.admin? && Animal.find(params[:id]).owner != current_user
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
    def image_select(animal)
        return animal.profile_picture if animal.profile_picture.attached?
        #use placeholder if no img attached
        return "animal_placeholder.png"
    end

    def user_is_sanctuary_and_owner(animal)
        current_user&.sanctuary? && animal.owner_id == current_user&.id && current_user&.approved?
    end

    def user_is_animal_sponsor(animal)
        current_user&.sponsor? && animal&.sponsorship&.sponsor == current_user
    end
end

app/views/animals/_card.html.erb
<%= image_tag image_select(animal),  class: "img-fluid", id: "card-pic" %>
<h3><%= animal.name %></h3>

app/views/animals/_form.html.erb
<%= form_with(model: animal) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
        <% animal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :year_born %>
    <%= form.number_field :year_born, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :weight, "Weight(kg)" %>
    <%= form.number_field :weight, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :bio %>
    <%= form.text_area :bio, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :species %>
    <%= form.text_field :species, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :sponsor_price %>
    <%= form.number_field :sponsor_price, class: "form-control", step: 0.01 %>
  </div>

  <div class="form-group">
    <%= form.label :category_id, "Category" %>
    <%= form.select :category_id, @categories.map {|c| [c.name, c.id]}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :profile_picture, "Animal Profile Picture" %>
    <%= form.file_field :profile_picture, accept: "image/jpg,image/png", class: "form-control-file" %>
  </div>

  <% if current_user.admin? %>
    <div class="form-check">
      <%= form.check_box :sponsored, class: "form-check-input" %>
      <%= form.label :sponsored, class: "form-check-label" %>
    </div>

    <div class="form-group">
      <%= form.label :owner_id %>
      <%= form.number_field :owner_id, class: "form-control" %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<% content_for(:html_title) { "#{@animal.name} - Edit" } %>
<h1>Editing Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<% content_for(:html_title) { 'Animals' } %>
<main class="container">
  <div class="row justify-content-center">
    <h1>Animals</h1>
  </div>
  <div class="row mt-5 justify-content-center">
    <h3>Search</h3>
  </div>
  <div class="row justify-content-center">
    <%= form_with url: animals_path, method: :get, class: "w-100" do |form| %>
      <div class="row justify-content-center">
        <div class="form-group col text-right">
          <h4>Category:</h4>
          <div class="form-check form-check-inline">
            <%= form.radio_button :category, "all", class: "form-check-input" %> 
            <%= form.label :category, "All", class: "form-check-label"%> 
          </div>
          <% @categories.each do |cat| %>
            <div class="form-check form-check-inline">
              <%= form.radio_button :category, cat.id, class: "form-check-input" %> 
              <%= form.label :category, cat.name, class: "form-check-label" %>
            </div>
          <% end %>
        </div>
        <div class="form-group col text-left ml-5">
          <h4>Sponsored?</h4>
          <div class="form-check form-check-inline">
            <%= form.radio_button :sponsored, 2, class: "form-check-input" %>
            <%= form.label :sponsored, "All", class: "form-check-label" %>
          </div>
          <div class="form-check form-check-inline">
            <%= form.radio_button :sponsored, 1, class: "form-check-input" %>
            <%= form.label :sponsored, "Yes", class: "form-check-label" %>
          </div>
          <div class="form-check form-check-inline">
            <%= form.radio_button :sponsored, 0, class: "form-check-input" %>
            <%= form.label :sponsored, "No", class: "form-check-label" %>
          </div>
        </div>
      </div>
      <div class="form-group row justify-content-center">
        <h4>Already know who you're looking for?</h4>
        <%= form.text_field :name, class: "form-control", placeholder: "Animal's Name" %>
      </div>
      <div class="form-group row justify-content-center">
        <%= form.submit "Search" %>
      </div>
    <% end %>
    <%= link_to "Reset Search", animals_path %>
  </div>
  <div class="row justify-content-center mt-5">
    <h3 class="mb-3 d-block text-center w-100">Animals Found</h3>
    <section class="d-flex flex-wrap justify-content-center">
      <% @animals.each do |animal| %>
        <div class="text-center mr-3" style="min-width: 150px; width: 16%;">
          <%= link_to animal_path(animal) do%>
            <%= render partial: "animals/card", locals: {animal: animal}, class: "text-primary"%>
          <% end %>
        </div>
      <% end %>
    </section>
  </div>
</main>

app/views/animals/new.html.erb
<% content_for(:html_title) { 'Animal - New' } %>
<main class="container w-50">
    <h1>Your Animal</h1>

    <%= render 'form', animal: @animal %>

    <%= link_to 'Back', animals_path %>
</main>

app/views/animals/show.html.erb
<% content_for(:html_title) { "#{@animal.name}" } %>
<main class="container">
  <div class="row">
    <div class="col text-center">
      <h3><%=@animal.name%></h3>
      <%= image_tag image_select(@animal), class: "mb-3", style: "width: 25%; min-width: 300px;" %>
      <h5>Bio:</h5>
      <p><%=@animal.bio%></p>
      <% if (current_user&.admin? || user_is_sanctuary_and_owner(@animal)) %>
        <%= link_to 'Edit', edit_animal_path(@animal), class: "mr-3" %>
        <%= link_to "Delete", animal_path, method: :delete %>
      <% end %>
    </div>
    <div class="col"> 
      <p>
        <strong>Age:</strong>
        <%= @animal.get_age %>
      </p>
      <p>
        <strong>Weight:</strong>
        <%= @animal.weight %>
      </p>
      <p>
        <strong>Species:</strong>
        <%= @animal.species %>
      </p>
      <p>
        <strong>Location:</strong>
        <%= @animal.owner.get_simple_location %>
      </p>
      <p>
        <strong>Category:</strong>
        <%= @animal.category.name %>
      </p>
      <% if @animal.sponsored%>
        <p>
          <strong>Sponsored by: </strong>
          <%= @animal.sponsorship.sponsor.first_name %>
          <% if user_is_animal_sponsor(@animal) || user_is_sanctuary_and_owner(@animal) || current_user&.admin? %>
            Sponsored At: <%= @animal.sponsorship.created_at %>
            Sponsorship Ends At: <%= @animal.sponsorship.created_at + 1.year %>
          <% end %>
        </p>
      <% end %>
      <p>
        <strong>Owner:</strong>
        <%= @animal.owner.full_name %>
      </p>
      <% if !current_user&.sanctuary? && !@animal.sponsored? %>
        <h5>Sponsor for 1 Year:</h5>
        <%=button_to "Sponsor: $#{@animal.sponsor_price / 100.0}", create_payment_path, method: :post, remote: true, params: {id: @animal.id} %>
      <% end %>
      <%= link_to 'Back', animals_path %>
    </div>
    <div class="col-6 text-center">
      <% if (current_user&.admin? || user_is_sanctuary_and_owner(@animal) || user_is_animal_sponsor(@animal))%>
        <h3>Uploads by Owner</h3>
        <div class="d-flex flex-wrap justify-content-center mt-5">
          <% @animal.media.each do |media| %>
            <div style="width: 40%" class="d-flex flex-column justify-content-end">
              <%= image_tag media, class: "w-100 img-thumbnail"%>
              <% if (current_user&.admin? || user_is_sanctuary_and_owner(@animal)) %>
                <%= link_to "Delete Image", animals_media_path(:id => @animal, :media_id => media.id), method: :delete, data: {confirm: "Are you sure?"}, class: "d-block" %>
              <% end %>
            </div>
          <% end %>
        </div>
        <% if (current_user&.admin? || user_is_sanctuary_and_owner(@animal)) %>
          <%= form_with url: animals_media_path(@animal), method: :post do |form| %>
            <div class="form-group text-left mt-3">
              <%= form.label :media, "Add More Photos" %>
              <%= form.file_field :media, multiple: true, accept: "image/jpg,image/png", class: "form-control-file" %>
              <%= form.submit "Add Photos", class: "mt-3" %>
            </div>
          <% end %>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="row mt-5 justify-content-center flex-column align-items-center">
    <% if (@animal.sponsorship && (current_user&.admin? || user_is_sanctuary_and_owner(@animal) || user_is_animal_sponsor(@animal)))%>
    <p>Have a question about <%=@animal.name%>, or want to request a photo. Chat below: </p>
      <div class="border border-primary p-2 w-50">
        <% @animal.sponsorship.chat.messages.each do |msg| %>
          <p class=<%=current_user&.id == msg.sender.id ? "text-left" : "text-right" %>><%=msg.sender.first_name %> - <%=msg.body%></p>
        <% end %>
        <%= form_with url: new_message_path(@animal), method: :post, class: "mt-5" do |form|%>
          <div class="form-group text-center">
            <%= form.label :message, "New Message:" %>
            <%= form.text_area :message, class: "form-control" %>
            <%= form.submit "Send Message" %>
          </div>
        <% end %>
      </div>
    <% end %>

  
    
  </div>
</main>